"""
PathForge — Notification Engine™ Models
========================================
Domain models for the Notification Engine — an event-driven, proactive
career alert system that surfaces actionable intelligence from all 12
engines with severity-based filtering, digest scheduling, and quiet
hours support.

Models:
    CareerNotification          — Individual career notification
    NotificationPreference      — User notification settings
    NotificationDigest          — Scheduled digest records

Enums:
    NotificationType  — threat | opportunity | milestone | insight | action_required
    Severity          — low | medium | high | critical
    DigestFrequency   — daily | weekly

Proprietary Innovations:
    🔥 Career-Aware Notifications™ — AI-driven alerts from 12 engines
    🔥 Severity-Based Filtering    — Min severity + engine-level toggles
    🔥 Quiet Hours Support         — Time-window notification suppression
"""

from __future__ import annotations

import datetime
import enum
from datetime import time
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    Time,
)
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from app.models.user import User


# ── Enums ──────────────────────────────────────────────────────


class NotificationType(enum.StrEnum):
    """Category of career notification."""

    THREAT = "threat"                      # Risk or threat detected
    OPPORTUNITY = "opportunity"            # New opportunity surfaced
    MILESTONE = "milestone"                # Achievement or milestone reached
    INSIGHT = "insight"                    # Informational career insight
    ACTION_REQUIRED = "action_required"    # User action needed


class Severity(enum.StrEnum):
    """Notification severity level."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class DigestFrequency(enum.StrEnum):
    """Notification digest scheduling frequency."""

    DAILY = "daily"
    WEEKLY = "weekly"


# ── CareerNotification ─────────────────────────────────────────


class CareerNotification(Base, UUIDMixin, TimestampMixin):
    """Notification Engine™ — Individual Career Notification.

    Event-driven notifications generated by engine analyses. Each
    notification is typed, severity-graded, and traceable to its
    source engine for full transparency.

    Lifecycle: created → displayed → read → (archived)
    """

    __tablename__ = "notif_career_notifications"

    # ── Foreign keys ──
    user_id: Mapped[str] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Core fields ──
    source_engine: Mapped[str] = mapped_column(
        String(100), nullable=False, index=True,
    )
    notification_type: Mapped[str] = mapped_column(
        String(30), default=NotificationType.INSIGHT.value,
        server_default="insight", nullable=False, index=True,
    )
    severity: Mapped[str] = mapped_column(
        String(20), default=Severity.LOW.value,
        server_default="low", nullable=False, index=True,
    )

    # ── Content fields ──
    title: Mapped[str] = mapped_column(
        String(500), nullable=False,
    )
    body: Mapped[str] = mapped_column(
        Text, nullable=False, default="",
    )
    action_url: Mapped[str | None] = mapped_column(
        String(500), nullable=True,
    )

    # ── Read state ──
    is_read: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false", nullable=False,
    )
    read_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )

    # ── Engine-specific context ──
    metadata_: Mapped[dict[str, Any] | None] = mapped_column(
        "metadata", JSON, nullable=True,
    )

    # ── Relationships ──
    user: Mapped[User] = relationship("User")

    def __repr__(self) -> str:
        return (
            f"<CareerNotification(type={self.notification_type}, "
            f"severity={self.severity}, read={self.is_read})>"
        )


# ── NotificationPreference ────────────────────────────────────


class NotificationPreference(Base, UUIDMixin, TimestampMixin):
    """Notification Engine™ — User Notification Settings.

    Full user control over notification behavior:
    - Per-engine toggles via enabled_engines list
    - Minimum severity threshold
    - Digest scheduling (daily/weekly)
    - Quiet hours window (time-based suppression)
    - Forward-compat fields for email delivery (Sprint 23)
    """

    __tablename__ = "notif_preferences"

    # ── Foreign keys ──
    user_id: Mapped[str] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )

    # ── Engine toggles ──
    enabled_engines: Mapped[dict[str, Any] | None] = mapped_column(
        JSON, nullable=True,
    )

    # ── Severity filter ──
    min_severity: Mapped[str] = mapped_column(
        String(20), default=Severity.LOW.value,
        server_default="low", nullable=False,
    )

    # ── Digest settings ──
    digest_enabled: Mapped[bool] = mapped_column(
        Boolean, default=True, server_default="true", nullable=False,
    )
    digest_frequency: Mapped[str] = mapped_column(
        String(20), default=DigestFrequency.WEEKLY.value,
        server_default="weekly", nullable=False,
    )

    # ── Quiet hours ──
    quiet_hours_start: Mapped[time | None] = mapped_column(
        Time, nullable=True,
    )
    quiet_hours_end: Mapped[time | None] = mapped_column(
        Time, nullable=True,
    )

    # ── Delivery channels ──
    in_app_notifications: Mapped[bool] = mapped_column(
        Boolean, default=True, server_default="true", nullable=False,
    )
    email_notifications: Mapped[bool] = mapped_column(
        Boolean, default=True, server_default="true", nullable=False,
    )
    push_notifications: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false", nullable=False,
    )

    # ── Push rate tracking (Sprint 33 F4) ──
    daily_push_count: Mapped[int] = mapped_column(
        Integer, default=0, server_default="0", nullable=False,
    )
    last_push_date: Mapped[datetime.date | None] = mapped_column(
        Date, nullable=True,
    )

    # ── Relationships ──
    user: Mapped[User] = relationship("User")

    def __repr__(self) -> str:
        return (
            f"<NotificationPreference(user_id={self.user_id}, "
            f"min_severity={self.min_severity}, "
            f"digest={self.digest_frequency})>"
        )


# ── NotificationDigest ─────────────────────────────────────────


class NotificationDigest(Base, UUIDMixin, TimestampMixin):
    """Notification Engine™ — Scheduled Digest Record.

    Aggregates unread notifications into periodic digest summaries.
    Supports daily and weekly frequencies. The summary field contains
    a JSON structure with notification counts per engine and severity.
    """

    __tablename__ = "notif_digests"

    # ── Foreign keys ──
    user_id: Mapped[str] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Digest fields ──
    digest_type: Mapped[str] = mapped_column(
        String(20), default=DigestFrequency.WEEKLY.value,
        server_default="weekly", nullable=False,
    )
    period_start: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
    )
    period_end: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
    )
    notification_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0,
    )
    summary: Mapped[dict[str, Any] | None] = mapped_column(
        JSON, nullable=True,
    )

    # ── Delivery tracking ──
    sent_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None,
    )

    # ── Relationships ──
    user: Mapped[User] = relationship("User")

    def __repr__(self) -> str:
        return (
            f"<NotificationDigest(type={self.digest_type}, "
            f"count={self.notification_count}, "
            f"period={self.period_start}..{self.period_end})>"
        )
