"""
PathForge — Webhook Replay Service (T6 / Sprint 58, ADR-0010)
================================================================

Persistence + replay surface for the operational webhook ledger.
Three roles:

1. **Persist** — every webhook receiver calls
   :meth:`WebhookReplayService.persist` on entry to write a
   ``received`` row.  Idempotent on ``(provider, event_id)`` so a
   provider retry doesn't duplicate.
2. **Outcome transitions** — after the receiver's business logic
   succeeds it calls :meth:`mark_processed`; on exception it calls
   :meth:`mark_failed` which increments ``retry_count`` and routes to
   ``dlq`` after :data:`MAX_RETRY_ATTEMPTS` strikes.
3. **Replay** — the admin DLQ surface calls :meth:`replay(ledger_id,
   handler=…)` to retry a DLQ entry through a caller-supplied handler.
   Success transitions to ``processed``; failure keeps the row in
   ``dlq`` and refreshes ``last_error``.

Distinct from :class:`app.models.subscription.BillingEvent` — that's
the billing-domain summary; this is the SRE/DLQ surface.
"""

from __future__ import annotations

import logging
import uuid
from collections.abc import Awaitable, Callable
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.webhook_event import WebhookEvent, WebhookOutcome

logger = logging.getLogger(__name__)

#: Number of failures (inclusive) before a row routes to DLQ.
#: Three matches Sentry's webhook retry policy — by the time a
#: provider has retried thrice and we've still failed, the issue is
#: server-side and an operator needs to look.
MAX_RETRY_ATTEMPTS: int = 3

#: Cap on persisted error strings.  Most provider exceptions are
#: short; pathological cases (full SQL traces, deserialised JSON
#: dumps) bloat the row + index.  2 KB is enough to identify the
#: error class without paging out of the row's TOAST page.
_MAX_ERROR_LEN: int = 2_000

#: Handler signature consumed by :meth:`replay`.  Pure function from
#: ``(event_type, payload)`` to nothing; raise on failure.
ReplayHandler = Callable[[str, dict[str, Any]], Awaitable[None]]


class WebhookReplayError(RuntimeError):
    """Raised by :meth:`replay` when the supplied handler fails.

    Distinct from the underlying exception so admin tooling can
    branch on the replay-vs-pristine path even when the handler raises
    a generic ``Exception``.
    """


class WebhookReplayService:
    """Per-session helper around :class:`WebhookEvent`."""

    def __init__(self, db: AsyncSession) -> None:
        self._db = db

    # ── Persist + transition ─────────────────────────────────

    async def persist(
        self,
        *,
        provider: str,
        event_id: str,
        event_type: str,
        payload: dict[str, Any],
    ) -> uuid.UUID:
        """Idempotent INSERT against the ``(provider, event_id)`` natural
        key.  Returns the ledger row's UUID — same value for repeat
        calls with the same key."""
        existing = await self._lookup(provider=provider, event_id=event_id)
        if existing is not None:
            return existing.id

        row = WebhookEvent(
            provider=provider,
            event_id=event_id,
            event_type=event_type,
            payload=payload,
            outcome=WebhookOutcome.received.value,
            retry_count=0,
        )
        self._db.add(row)
        # Flush so the autogenerated UUID is materialised; callers
        # frequently want the id immediately for breadcrumb tagging.
        await self._db.flush()
        assert row.id is not None
        return row.id

    async def mark_processed(self, ledger_id: uuid.UUID) -> None:
        """Transition a row to ``processed``.  Idempotent — calling
        twice is a no-op the second time."""
        row = await self._get(ledger_id)
        row.outcome = WebhookOutcome.processed.value
        row.last_attempt_at = datetime.now(UTC)

    async def mark_failed(self, ledger_id: uuid.UUID, *, error: str) -> None:
        """Increment ``retry_count``, refresh ``last_error`` /
        ``last_attempt_at``, and route to ``dlq`` once
        :data:`MAX_RETRY_ATTEMPTS` is reached."""
        row = await self._get(ledger_id)
        row.retry_count += 1
        row.last_error = _truncate(error)
        row.last_attempt_at = datetime.now(UTC)
        if row.retry_count >= MAX_RETRY_ATTEMPTS:
            row.outcome = WebhookOutcome.dlq.value
            logger.warning(
                "webhook_event %s routed to DLQ after %d attempts (%s)",
                row.id,
                row.retry_count,
                _truncate(error, cap=200),
            )
        else:
            row.outcome = WebhookOutcome.failed.value

    # ── Admin surface ────────────────────────────────────────

    async def list_dlq(self, *, limit: int = 100) -> list[WebhookEvent]:
        """Return DLQ entries newest-first.

        Convenience wrapper around :meth:`list_events` for the most
        common operator query — kept on the public surface so tests
        and callers that already pin to it don't break.
        """
        return await self.list_events(status=WebhookOutcome.dlq, limit=limit)

    async def list_events(
        self,
        *,
        status: str | WebhookOutcome,
        limit: int = 100,
    ) -> list[WebhookEvent]:
        """Return ledger entries for ``status``, newest-first.

        Centralises status-based listing so the route layer doesn't
        re-implement the query (Gemini medium — separation of concerns).
        Accepts either the raw string or the :class:`WebhookOutcome`
        enum so both call sites stay ergonomic.
        """
        outcome_value = (
            status.value if isinstance(status, WebhookOutcome) else status
        )
        stmt = (
            select(WebhookEvent)
            .where(WebhookEvent.outcome == outcome_value)
            .order_by(WebhookEvent.created_at.desc())
            .limit(limit)
        )
        result = await self._db.execute(stmt)
        return list(result.scalars().all())

    async def replay(
        self,
        ledger_id: uuid.UUID,
        *,
        handler: ReplayHandler,
    ) -> None:
        """Re-run ``handler`` against the persisted payload.

        On success → row transitions to ``processed``.  On failure →
        row stays at ``dlq``, ``last_error`` refreshes, and a
        :class:`WebhookReplayError` is raised so the admin caller can
        branch on it.
        """
        row = await self._get(ledger_id)
        try:
            await handler(row.event_type, row.payload)
        except Exception as exc:
            row.last_error = _truncate(str(exc))
            row.last_attempt_at = datetime.now(UTC)
            # Keep outcome at dlq — replay failure is "we tried, still
            # broken", not "back to the failed/retry-pool path".
            row.outcome = WebhookOutcome.dlq.value
            logger.warning("webhook_event %s replay failed: %s", row.id, exc)
            raise WebhookReplayError(f"Replay of {row.id} failed: {exc!s}") from exc
        row.outcome = WebhookOutcome.processed.value
        row.last_attempt_at = datetime.now(UTC)

    # ── Internals ────────────────────────────────────────────

    async def _lookup(
        self,
        *,
        provider: str,
        event_id: str,
    ) -> WebhookEvent | None:
        stmt = select(WebhookEvent).where(
            WebhookEvent.provider == provider,
            WebhookEvent.event_id == event_id,
        )
        return (await self._db.execute(stmt)).scalar_one_or_none()

    async def _get(self, ledger_id: uuid.UUID) -> WebhookEvent:
        stmt = select(WebhookEvent).where(WebhookEvent.id == ledger_id)
        row = (await self._db.execute(stmt)).scalar_one_or_none()
        if row is None:
            raise WebhookReplayError(f"webhook_event {ledger_id} not found")
        return row


def _truncate(text: str, *, cap: int = _MAX_ERROR_LEN) -> str:
    """Truncate ``text`` to ``cap`` characters with a single-char
    ellipsis marker (so the row knows it was truncated and the index
    builder doesn't waste space on duplicate prefixes)."""
    if len(text) <= cap:
        return text
    return text[:cap] + "…"


__all__ = [
    "MAX_RETRY_ATTEMPTS",
    "ReplayHandler",
    "WebhookReplayError",
    "WebhookReplayService",
]
