"""create delivery layer tables

Revision ID: 0c2d3e4f5g6h
Revises: 0b1c2d3e4f5g
Create Date: 2026-02-24 16:45:00.000000+01:00

Sprint 23 — Phase D: Delivery Layer
Creates 8 tables for:
  - Cross-Engine Recommendation Intelligence™ (4 tables)
  - Career Workflow Automation Engine™ (4 tables)
"""

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON, UUID

from alembic import op

# revision identifiers
revision = "0c2d3e4f5g6h"
down_revision = "0b1c2d3e4f5g"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create 8 Delivery Layer tables."""
    # ── 1. ri_batches (Recommendation Intelligence™) ──────────
    #    Created first because ri_recommendations has FK to this table.
    op.create_table(
        "ri_batches",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "batch_type",
            sa.String(40),
            nullable=False,
            server_default="manual",
        ),
        sa.Column("engine_snapshot", JSON, nullable=True),
        sa.Column(
            "total_recommendations",
            sa.Integer,
            nullable=False,
            server_default="0",
        ),
        sa.Column("career_vitals_at_generation", sa.Float, nullable=True),
        sa.Column(
            "data_source",
            sa.String(200),
            nullable=False,
            server_default="Intelligence Fusion Engine™ — batch analysis run",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # ── 2. ri_recommendations (Recommendation Intelligence™) ──
    op.create_table(
        "ri_recommendations",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "batch_id",
            UUID(as_uuid=True),
            sa.ForeignKey("ri_batches.id", ondelete="SET NULL"),
            nullable=True,
            index=True,
        ),
        sa.Column(
            "recommendation_type",
            sa.String(40),
            nullable=False,
            server_default="opportunity",
            index=True,
        ),
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            server_default="pending",
            index=True,
        ),
        sa.Column(
            "effort_level",
            sa.String(30),
            nullable=False,
            server_default="moderate",
        ),
        sa.Column("priority_score", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("urgency", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("impact_score", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("confidence_score", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column("action_items", JSON, nullable=True),
        sa.Column("source_engines", JSON, nullable=True),
        sa.Column(
            "data_source",
            sa.String(200),
            nullable=False,
            server_default=(
                "Intelligence Fusion Engine™ — cross-engine recommendation"
            ),
        ),
        sa.Column(
            "disclaimer",
            sa.String(500),
            nullable=False,
            server_default=(
                "This recommendation is AI-generated by correlating signals "
                "from multiple intelligence engines. Priority scores are "
                "estimates, not guarantees. Use alongside your own judgment."
            ),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "priority_score >= 0.0 AND priority_score <= 100.0",
            name="ck_ri_rec_priority_score_range",
        ),
        sa.CheckConstraint(
            "confidence_score >= 0.0 AND confidence_score <= 0.85",
            name="ck_ri_rec_confidence_cap",
        ),
    )

    # ── 3. ri_correlations (Recommendation Intelligence™) ─────
    op.create_table(
        "ri_correlations",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "recommendation_id",
            UUID(as_uuid=True),
            sa.ForeignKey("ri_recommendations.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column("engine_name", sa.String(100), nullable=False),
        sa.Column("correlation_strength", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("insight_summary", sa.Text, nullable=False, server_default=""),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "correlation_strength >= 0.0 AND correlation_strength <= 1.0",
            name="ck_ri_corr_strength_range",
        ),
    )

    # ── 4. ri_preferences (Recommendation Intelligence™) ──────
    op.create_table(
        "ri_preferences",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
            index=True,
        ),
        sa.Column("enabled_categories", JSON, nullable=True),
        sa.Column(
            "min_priority_threshold",
            sa.Float,
            nullable=False,
            server_default="0.0",
        ),
        sa.Column(
            "max_recommendations_per_batch",
            sa.Integer,
            nullable=False,
            server_default="10",
        ),
        sa.Column("preferred_effort_levels", JSON, nullable=True),
        sa.Column(
            "notifications_enabled",
            sa.Boolean,
            nullable=False,
            server_default="true",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # ── 5. wf_workflows (Workflow Automation Engine™) ─────────
    op.create_table(
        "wf_workflows",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column("name", sa.String(300), nullable=False),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column(
            "workflow_status",
            sa.String(20),
            nullable=False,
            server_default="draft",
            index=True,
        ),
        sa.Column(
            "trigger_type",
            sa.String(30),
            nullable=False,
            server_default="manual",
            index=True,
        ),
        sa.Column("trigger_config", JSON, nullable=True),
        sa.Column("total_steps", sa.Integer, nullable=False, server_default="0"),
        sa.Column("completed_steps", sa.Integer, nullable=False, server_default="0"),
        sa.Column(
            "is_template",
            sa.Boolean,
            nullable=False,
            server_default="false",
        ),
        sa.Column("template_category", sa.String(100), nullable=True),
        sa.Column("source_engine", sa.String(100), nullable=True),
        sa.Column("source_recommendation_id", sa.String(100), nullable=True),
        sa.Column(
            "data_source",
            sa.String(200),
            nullable=False,
            server_default=(
                "Career Workflow Automation Engine™ — automated career pipeline"
            ),
        ),
        sa.Column(
            "disclaimer",
            sa.String(500),
            nullable=False,
            server_default=(
                "This workflow is AI-generated based on career intelligence "
                "signals. Steps are suggestions, not mandates. Adjust or "
                "skip steps based on your own judgment and circumstances."
            ),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "total_steps >= 0",
            name="ck_wf_workflow_total_steps_positive",
        ),
    )

    # ── 6. wf_steps (Workflow Automation Engine™) ─────────────
    op.create_table(
        "wf_steps",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workflow_id",
            UUID(as_uuid=True),
            sa.ForeignKey("wf_workflows.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column("step_order", sa.Integer, nullable=False, server_default="0"),
        sa.Column(
            "step_type",
            sa.String(20),
            nullable=False,
            server_default="action",
        ),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column(
            "is_completed",
            sa.Boolean,
            nullable=False,
            server_default="false",
        ),
        sa.Column(
            "is_skipped",
            sa.Boolean,
            nullable=False,
            server_default="false",
        ),
        sa.Column("action_config", JSON, nullable=True),
        sa.Column("condition_config", JSON, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "step_order >= 0",
            name="ck_wf_step_order_positive",
        ),
    )

    # ── 7. wf_executions (Workflow Automation Engine™) ────────
    op.create_table(
        "wf_executions",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workflow_id",
            UUID(as_uuid=True),
            sa.ForeignKey("wf_workflows.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column("trigger_context", JSON, nullable=True),
        sa.Column("career_vitals_at_trigger", sa.Float, nullable=True),
        sa.Column(
            "execution_status",
            sa.String(20),
            nullable=False,
            server_default="running",
        ),
        sa.Column("steps_completed", sa.Integer, nullable=False, server_default="0"),
        sa.Column("steps_total", sa.Integer, nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # ── 8. wf_preferences (Workflow Automation Engine™) ───────
    op.create_table(
        "wf_preferences",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
            index=True,
        ),
        sa.Column(
            "automation_enabled",
            sa.Boolean,
            nullable=False,
            server_default="true",
        ),
        sa.Column(
            "max_concurrent_workflows",
            sa.Integer,
            nullable=False,
            server_default="5",
        ),
        sa.Column(
            "auto_activate_templates",
            sa.Boolean,
            nullable=False,
            server_default="false",
        ),
        sa.Column(
            "trigger_sensitivity",
            sa.String(20),
            nullable=False,
            server_default="medium",
        ),
        sa.Column("enabled_trigger_types", JSON, nullable=True),
        sa.Column(
            "notifications_enabled",
            sa.Boolean,
            nullable=False,
            server_default="true",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )


def downgrade() -> None:
    """Drop all 8 Delivery Layer tables in reverse order."""
    op.drop_table("wf_preferences")
    op.drop_table("wf_executions")
    op.drop_table("wf_steps")
    op.drop_table("wf_workflows")
    op.drop_table("ri_preferences")
    op.drop_table("ri_correlations")
    op.drop_table("ri_recommendations")
    op.drop_table("ri_batches")
